/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.sem.pkg1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bouoron
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        
        txtDay.setEnabled(false);
        txtDay.setText("N/A");
        txtCustomerPass.setEnabled(false);
        txtCustomerPass.setText("N/A");
        
        String filePath = "Customer.txt";
        File file = new File(filePath);
    
        try {
            FileReader read = new FileReader(file);
            BufferedReader buffread = new BufferedReader(read);
            
            DefaultTableModel tablemode = (DefaultTableModel)tableCustomer.getModel();
            Object[] lines = buffread.lines().toArray();
            
            for(int i =0; i < lines.length; i++){
                String[] row = lines[i].toString().split("///");
                tablemode.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        txtCustomerPass = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        txtCustomerContactNum = new javax.swing.JTextField();
        btnCustomerCreate = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        boxGender3 = new javax.swing.JComboBox<>();
        btnCustomerDelete = new javax.swing.JButton();
        btnCustomerUpdate = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        btnCustomerClear = new javax.swing.JButton();
        btnCustomerback = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDay = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblimage2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        txtCustomerPass.setBackground(null);
        txtCustomerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPassActionPerformed(evt);
            }
        });

        txtCustomerName.setBackground(null);
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        txtCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyTyped(evt);
            }
        });

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Customer Password:");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Customer Name:");

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Gender:");

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Contact Number:");

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Address:");

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Email:");

        txtCustomerEmail.setBackground(null);

        txtCustomerContactNum.setBackground(null);
        txtCustomerContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerContactNumActionPerformed(evt);
            }
        });
        txtCustomerContactNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerContactNumKeyTyped(evt);
            }
        });

        btnCustomerCreate.setBackground(new java.awt.Color(0, 204, 204));
        btnCustomerCreate.setForeground(new java.awt.Color(0, 0, 0));
        btnCustomerCreate.setText("Create");
        btnCustomerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCreateActionPerformed(evt);
            }
        });

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Customer Password", "Gender", "Contact Number", "Address", "Email", "Available Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomerMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableCustomer);

        boxGender3.setBackground(null);
        boxGender3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        boxGender3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGender3ActionPerformed(evt);
            }
        });

        btnCustomerDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnCustomerDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnCustomerDelete.setText("Remove");
        btnCustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDeleteActionPerformed(evt);
            }
        });

        btnCustomerUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnCustomerUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnCustomerUpdate.setText("Update");
        btnCustomerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerUpdateActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Customer Account Management");

        btnCustomerClear.setBackground(new java.awt.Color(0, 204, 204));
        btnCustomerClear.setForeground(new java.awt.Color(0, 0, 0));
        btnCustomerClear.setText("Clear");
        btnCustomerClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerClearActionPerformed(evt);
            }
        });

        btnCustomerback.setBackground(new java.awt.Color(0, 204, 204));
        btnCustomerback.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnCustomerback.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerback.setText("Back");
        btnCustomerback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerbackActionPerformed(evt);
            }
        });

        txtDay.setBackground(java.awt.Color.white);
        txtDay.setColumns(20);
        txtDay.setRows(5);
        txtDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDayKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(txtDay);

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Available day:");

        txtCustomerAddress.setBackground(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCustomerback)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel35))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCustomerEmail))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxGender3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCustomerContactNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCustomerPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(btnCustomerCreate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCustomerUpdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCustomerDelete)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCustomerClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel34)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(boxGender3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtCustomerContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCustomerDelete)
                            .addComponent(btnCustomerCreate)
                            .addComponent(btnCustomerUpdate)
                            .addComponent(btnCustomerClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnCustomerback))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Manager name");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("✺");

        lblimage2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblimage2.setForeground(new java.awt.Color(255, 255, 255));
        lblimage2.setText("APU Hostel Appliances Service Centre");

        jLabel16.setBackground(new java.awt.Color(0, 204, 204));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("X");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(4, 4, 4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblimage2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(jLabel16))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblimage2)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPassActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed

    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyTyped
        char d = evt.getKeyChar();

        if(Character.isDigit(d)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCustomerNameKeyTyped

    private void txtCustomerContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerContactNumActionPerformed

    private void txtCustomerContactNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerContactNumKeyTyped
        char t = evt.getKeyChar();

        if(!Character.isDigit(t)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCustomerContactNumKeyTyped

    private void btnCustomerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCreateActionPerformed
        if(txtCustomerName.getText().equals("")||txtCustomerPass.getText().equals("")|| boxGender3.getSelectedItem().equals("")|| txtCustomerContactNum.getText().equals("")|| txtCustomerAddress.getText().equals("")|| txtCustomerEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill in all Blank Textbox");
        }else{
            String s = "";
            boolean exists = false;
            for (int i = 0; i < tableCustomer.getRowCount(); i++){
                s = tableCustomer.getValueAt(i, 0).toString().trim();
            
                if(txtCustomerName.getText().equals(s)){
                    exists = true;
                    JOptionPane.showMessageDialog(null, "Name Exist, type another Name Please");
                    txtCustomerName.setText("");
                    
                    break;
                }
            }if(exists == false){
            String TechData[] = {txtCustomerName.getText(),txtCustomerPass.getText(),boxGender3.getSelectedItem().toString(),txtCustomerContactNum.getText(),txtCustomerAddress.getText(),txtCustomerEmail.getText(),txtDay.getText()};

            DefaultTableModel table = (DefaultTableModel)tableCustomer.getModel();

            table.addRow(TechData);

            String filePath = "Customer.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);

                for(int i = 0; i < tableCustomer.getRowCount(); i++){
                    for(int p = 0; p < tableCustomer.getColumnCount(); p++){
                        buffwrite.write(tableCustomer.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }

                buffwrite.close();
                write.close();

            } catch (IOException ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this,"Created new Customer Account Successfully");
            txtCustomerName.setText("");
            txtCustomerContactNum.setText("");
            txtCustomerAddress.setText("");
            txtCustomerEmail.setText("");
            
            }
        }
    }//GEN-LAST:event_btnCustomerCreateActionPerformed

    private void tableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomerMouseClicked

        DefaultTableModel table = (DefaultTableModel)tableCustomer.getModel();

        String tableName = table.getValueAt(tableCustomer.getSelectedRow(), 0).toString();
        String tablePass = table.getValueAt(tableCustomer.getSelectedRow(), 1).toString();
        String tableGen = table.getValueAt(tableCustomer.getSelectedRow(), 2).toString();
        for(int i = 0; i < boxGender3.getItemCount(); i++){
            if(boxGender3.getItemAt(i).equalsIgnoreCase(tableGen)){
                boxGender3.setSelectedIndex(i);
            }
        }
        String tableContactNum = table.getValueAt(tableCustomer.getSelectedRow(), 3).toString();
        String tableAddress = table.getValueAt(tableCustomer.getSelectedRow(), 4).toString();
        String tableEmail = table.getValueAt(tableCustomer.getSelectedRow(), 5).toString();
        String tableDay = table.getValueAt(tableCustomer.getSelectedRow(), 6).toString();
        btnCustomerCreate.setEnabled(false);
        txtCustomerName.setText(tableName);
        txtCustomerPass.setText(tablePass);
        txtCustomerContactNum.setText(tableContactNum);
        txtCustomerAddress.setText(tableAddress);
        txtCustomerEmail.setText(tableEmail);
        txtDay.setText(tableDay);
        txtCustomerName.setEnabled(false);
    }//GEN-LAST:event_tableCustomerMouseClicked

    private void boxGender3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGender3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGender3ActionPerformed

    private void btnCustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDeleteActionPerformed
        DefaultTableModel table = (DefaultTableModel)tableCustomer.getModel();

        if(tableCustomer.getSelectedRowCount()==1){
            table.removeRow(tableCustomer.getSelectedRow());

            String filePath = "Customer.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);

                for(int i = 0; i < tableCustomer.getRowCount(); i++){
                    for(int p = 0; p < tableCustomer.getColumnCount(); p++){
                        buffwrite.write(tableCustomer.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }

                buffwrite.close();
                write.close();

            } catch (IOException ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this, "Successfully removed");
            txtCustomerName.setText("");
            txtCustomerContactNum.setText("");
            txtCustomerAddress.setText("");
            txtCustomerEmail.setText("");
            txtCustomerName.setEnabled(true);
            btnCustomerCreate.setEnabled(true);

        }else{
            if(tableCustomer.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "There are no data left in the table");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row to remove");
            }
        }
    }//GEN-LAST:event_btnCustomerDeleteActionPerformed

    private void btnCustomerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerUpdateActionPerformed
        DefaultTableModel table = (DefaultTableModel)tableCustomer.getModel();

        if(txtCustomerName.getText().equals("")||txtCustomerPass.getText().equals("")|| boxGender3.getSelectedItem().equals("")|| txtCustomerContactNum.getText().equals("")|| txtCustomerAddress.getText().equals("")|| txtCustomerEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill in all Blank Textbox");
        }else if(tableCustomer.getSelectedRowCount() == 1){
            String Name = txtCustomerName.getText();
            String Password = txtCustomerPass.getText();
            String Gen = (String) boxGender3.getSelectedItem();
            String ContactNum = txtCustomerContactNum.getText();
            String Address = txtCustomerAddress.getText();
            String Email = txtCustomerEmail.getText();
            String Day = txtDay.getText();

            table.setValueAt(Name, tableCustomer.getSelectedRow(), 0);
            table.setValueAt(Password, tableCustomer.getSelectedRow(), 1);
            table.setValueAt(Gen, tableCustomer.getSelectedRow(), 2);
            table.setValueAt(ContactNum, tableCustomer.getSelectedRow(), 3);
            table.setValueAt(Address, tableCustomer.getSelectedRow(), 4);
            table.setValueAt(Email, tableCustomer.getSelectedRow(), 5);
            table.setValueAt(Day, tableCustomer.getSelectedRow(), 6);

            JOptionPane.showMessageDialog(this, "Successfully updated!!");

            txtCustomerName.setText("");
            txtCustomerContactNum.setText("");
            txtCustomerAddress.setText("");
            txtCustomerEmail.setText("");
            btnCustomerCreate.setEnabled(true);
            tableCustomer.clearSelection();
            txtCustomerName.setEnabled(true);

            String filePath = "Customer.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);

                for(int i = 0; i < tableCustomer.getRowCount(); i++){
                    for(int p = 0; p < tableCustomer.getColumnCount(); p++){
                        buffwrite.write(tableCustomer.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }

                buffwrite.close();
                write.close();

            } catch (IOException ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            if(table.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "There is no data on the table");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a list for update!");
            }
        }
    }//GEN-LAST:event_btnCustomerUpdateActionPerformed

    private void btnCustomerClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerClearActionPerformed

        txtCustomerName.setText("");
        txtCustomerContactNum.setText("");
        txtCustomerAddress.setText("");
        txtCustomerEmail.setText("");
        btnCustomerCreate.setEnabled(true);
        tableCustomer.clearSelection();
        txtCustomerName.setEnabled(true);
    }//GEN-LAST:event_btnCustomerClearActionPerformed

    private void btnCustomerbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerbackActionPerformed
        Main z = new Main();
        z.lblname.setText(lblname.getText());
        z.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCustomerbackActionPerformed

    private void txtDayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDayKeyTyped
       char v = evt.getKeyChar();

        if(Character.isDigit(v)){
            evt.consume();
        }
    }//GEN-LAST:event_txtDayKeyTyped

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGender3;
    private javax.swing.JButton btnCustomerClear;
    private javax.swing.JButton btnCustomerCreate;
    private javax.swing.JButton btnCustomerDelete;
    private javax.swing.JButton btnCustomerUpdate;
    private javax.swing.JButton btnCustomerback;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblimage2;
    public javax.swing.JLabel lblname;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerContactNum;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPass;
    private javax.swing.JTextArea txtDay;
    // End of variables declaration//GEN-END:variables
}
