/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.sem.pkg1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bouoron
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        
        txtDay.setEnabled(false);
        txtDay.setText("N/A");
        
        String filePath = "Manager.txt";
        File file = new File(filePath);
    
        try {
            FileReader read = new FileReader(file);
            BufferedReader buffread = new BufferedReader(read);
            
            DefaultTableModel tablemode = (DefaultTableModel)tableManager.getModel();
            Object[] lines = buffread.lines().toArray();
            
            for(int i =0; i < lines.length; i++){
                String[] row = lines[i].toString().split("///");
                tablemode.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtManagerPass = new javax.swing.JTextField();
        txtManagerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtManagerEmail = new javax.swing.JTextField();
        txtManagerContactNum = new javax.swing.JTextField();
        btnManagerCreate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableManager = new javax.swing.JTable();
        boxGender = new javax.swing.JComboBox<>();
        btnManagerDelete = new javax.swing.JButton();
        btnManagerUpdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnManagerClear = new javax.swing.JButton();
        btnManagerback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDay = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtManagerAddress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblimage2 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(java.awt.Color.white);

        txtManagerPass.setBackground(java.awt.Color.white);
        txtManagerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerPassActionPerformed(evt);
            }
        });

        txtManagerName.setBackground(java.awt.Color.white);
        txtManagerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerNameActionPerformed(evt);
            }
        });
        txtManagerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtManagerNameKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Manager Password:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Manager Name:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Gender:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contact Number:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Address:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email:");

        txtManagerEmail.setBackground(java.awt.Color.white);

        txtManagerContactNum.setBackground(java.awt.Color.white);
        txtManagerContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerContactNumActionPerformed(evt);
            }
        });
        txtManagerContactNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtManagerContactNumKeyTyped(evt);
            }
        });

        btnManagerCreate.setBackground(new java.awt.Color(0, 204, 204));
        btnManagerCreate.setForeground(new java.awt.Color(0, 0, 0));
        btnManagerCreate.setText("Create");
        btnManagerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerCreateActionPerformed(evt);
            }
        });

        tableManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manager Name", "Manager Password", "Gender", "Contact Number", "Address", "Email", "Available Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableManagerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableManager);

        boxGender.setBackground(java.awt.Color.white);
        boxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        boxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGenderActionPerformed(evt);
            }
        });

        btnManagerDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnManagerDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnManagerDelete.setText("Remove");
        btnManagerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerDeleteActionPerformed(evt);
            }
        });

        btnManagerUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnManagerUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnManagerUpdate.setText("Update");
        btnManagerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerUpdateActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Manager Account Management");

        btnManagerClear.setBackground(new java.awt.Color(0, 204, 204));
        btnManagerClear.setForeground(new java.awt.Color(0, 0, 0));
        btnManagerClear.setText("Clear");
        btnManagerClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerClearActionPerformed(evt);
            }
        });

        btnManagerback.setBackground(new java.awt.Color(0, 204, 204));
        btnManagerback.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnManagerback.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerback.setText("Back");
        btnManagerback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerbackActionPerformed(evt);
            }
        });

        txtDay.setBackground(java.awt.Color.white);
        txtDay.setColumns(20);
        txtDay.setRows(5);
        txtDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDayKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDay);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Available day:");

        txtManagerAddress.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10))
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtManagerContactNum)
                                            .addComponent(boxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtManagerPass)
                                            .addComponent(txtManagerEmail)
                                            .addComponent(txtManagerName)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtManagerAddress)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnManagerCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnManagerUpdate)
                                        .addGap(10, 10, 10)
                                        .addComponent(btnManagerDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnManagerClear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnManagerback, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManagerPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManagerContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtManagerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManagerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManagerCreate)
                            .addComponent(btnManagerDelete)
                            .addComponent(btnManagerUpdate)
                            .addComponent(btnManagerClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(btnManagerback)
                        .addContainerGap())))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("✺");

        lblimage2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblimage2.setForeground(new java.awt.Color(255, 255, 255));
        lblimage2.setText("APU Hostel Appliances Service Centre");

        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Manager");

        jLabel16.setBackground(new java.awt.Color(0, 204, 204));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("X");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblimage2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblname)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblimage2))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtManagerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerPassActionPerformed

    private void txtManagerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerNameActionPerformed

    }//GEN-LAST:event_txtManagerNameActionPerformed

    private void txtManagerNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManagerNameKeyTyped
        char d = evt.getKeyChar();

        if(Character.isDigit(d)){
            evt.consume();
        }
    }//GEN-LAST:event_txtManagerNameKeyTyped

    private void txtManagerContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerContactNumActionPerformed

    private void txtManagerContactNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManagerContactNumKeyTyped
        char t = evt.getKeyChar();

        if(!Character.isDigit(t)){
            evt.consume();
        }
    }//GEN-LAST:event_txtManagerContactNumKeyTyped

    private void btnManagerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerCreateActionPerformed
        if(txtManagerName.getText().equals("")||txtManagerPass.getText().equals("")|| boxGender.getSelectedItem().equals("")|| txtManagerContactNum.getText().equals("")|| txtManagerAddress.getText().equals("")|| txtManagerEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill in all Blank Textbox");
        }else{
            String s = "";
            boolean exists = false;
            for (int i = 0; i < tableManager.getRowCount(); i++){
                s = tableManager.getValueAt(i, 0).toString().trim();
            
                if(txtManagerName.getText().equals(s)){
                    exists = true;
                    JOptionPane.showMessageDialog(null, "Name Exist, type another Name Please");
                    txtManagerName.setText("");
                    
                    break;
                }
            }if(exists == false){
            
            
            String TechData[] = {txtManagerName.getText(),txtManagerPass.getText(),boxGender.getSelectedItem().toString(),txtManagerContactNum.getText(),txtManagerAddress.getText(),txtManagerEmail.getText(),txtDay.getText()};

            DefaultTableModel table = (DefaultTableModel)tableManager.getModel();

            table.addRow(TechData);

            String filePath = "Manager.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);

                for(int i = 0; i < tableManager.getRowCount(); i++){
                    for(int p = 0; p < tableManager.getColumnCount(); p++){
                        buffwrite.write(tableManager.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }

                buffwrite.close();
                write.close();

            } catch (IOException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this,"Created new Manager Account Successfully");
            txtManagerName.setText("");
            txtManagerPass.setText("");
            txtManagerContactNum.setText("");
            txtManagerAddress.setText("");
            txtManagerEmail.setText("");

        }
    }//GEN-LAST:event_btnManagerCreateActionPerformed
    }
    private void tableManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableManagerMouseClicked

        DefaultTableModel table = (DefaultTableModel)tableManager.getModel();

        String tableName = table.getValueAt(tableManager.getSelectedRow(), 0).toString();
        String tablePass = table.getValueAt(tableManager.getSelectedRow(), 1).toString();
        String tableGen = table.getValueAt(tableManager.getSelectedRow(), 2).toString();
        for(int i = 0; i < boxGender.getItemCount(); i++){
            if(boxGender.getItemAt(i).equalsIgnoreCase(tableGen)){
                boxGender.setSelectedIndex(i);
            }
        }
        String tableContactNum = table.getValueAt(tableManager.getSelectedRow(), 3).toString();
        String tableAddress = table.getValueAt(tableManager.getSelectedRow(), 4).toString();
        String tableEmail = table.getValueAt(tableManager.getSelectedRow(), 5).toString();
        String tableDay = table.getValueAt(tableManager.getSelectedRow(), 6).toString();
        btnManagerCreate.setEnabled(false);
        txtManagerName.setEnabled(false);
        txtManagerName.setText(tableName);
        txtManagerPass.setText(tablePass);
        txtManagerContactNum.setText(tableContactNum);
        txtManagerAddress.setText(tableAddress);
        txtManagerEmail.setText(tableEmail);
        txtDay.setText(tableDay);
    }//GEN-LAST:event_tableManagerMouseClicked

    private void boxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGenderActionPerformed

    private void btnManagerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerDeleteActionPerformed
        DefaultTableModel table = (DefaultTableModel)tableManager.getModel();

        if(tableManager.getSelectedRowCount()==1){
            table.removeRow(tableManager.getSelectedRow());

            String filePath = "Manager.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);

                for(int i = 0; i < tableManager.getRowCount(); i++){
                    for(int p = 0; p < tableManager.getColumnCount(); p++){
                        buffwrite.write(tableManager.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }

                buffwrite.close();
                write.close();

            } catch (IOException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this, "Successfully removed");
            txtManagerPass.setText("");
            txtManagerName.setText("");
            txtManagerContactNum.setText("");
            txtManagerAddress.setText("");
            txtManagerEmail.setText("");
            txtManagerName.setEnabled(true);
            btnManagerCreate.setEnabled(true);

        }else{
            if(tableManager.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "There are no data left in the table");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row to remove");
            }
        }
    }//GEN-LAST:event_btnManagerDeleteActionPerformed

    private void btnManagerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerUpdateActionPerformed
        DefaultTableModel table = (DefaultTableModel)tableManager.getModel();
        
        if(txtManagerName.getText().equals("")||txtManagerPass.getText().equals("")|| boxGender.getSelectedItem().equals("")|| txtManagerContactNum.getText().equals("")|| txtManagerAddress.getText().equals("")|| txtManagerEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill in all Blank Textbox");
        }else if(tableManager.getSelectedRowCount() == 1){
            String Name = txtManagerName.getText();
            String Password = txtManagerPass.getText();
            String Gen = (String) boxGender.getSelectedItem();
            String ContactNum = txtManagerContactNum.getText();
            String Address = txtManagerAddress.getText();
            String Email = txtManagerEmail.getText();
            String Day = txtDay.getText();

            table.setValueAt(Name, tableManager.getSelectedRow(), 0);
            table.setValueAt(Password, tableManager.getSelectedRow(), 1);
            table.setValueAt(Gen, tableManager.getSelectedRow(), 2);
            table.setValueAt(ContactNum, tableManager.getSelectedRow(), 3);
            table.setValueAt(Address, tableManager.getSelectedRow(), 4);
            table.setValueAt(Email, tableManager.getSelectedRow(), 5);
            table.setValueAt(Day, tableManager.getSelectedRow(), 6);

            JOptionPane.showMessageDialog(this, "Successfully updated!!");

            txtManagerPass.setText("");
            txtManagerName.setText("");
            txtManagerContactNum.setText("");
            txtManagerAddress.setText("");
            txtManagerEmail.setText("");
            btnManagerCreate.setEnabled(true);
            txtManagerName.setEnabled(true);
            tableManager.clearSelection();

            String filePath = "Manager.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);

                for(int i = 0; i < tableManager.getRowCount(); i++){
                    for(int p = 0; p < tableManager.getColumnCount(); p++){
                        buffwrite.write(tableManager.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }

                buffwrite.close();
                write.close();

            } catch (IOException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            if(table.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "There is no data on the table");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a list for update!");
            }
        }
    }//GEN-LAST:event_btnManagerUpdateActionPerformed

    private void btnManagerClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerClearActionPerformed
        txtManagerPass.setText("");
        txtManagerName.setText("");
        txtManagerContactNum.setText("");
        txtManagerAddress.setText("");
        txtManagerEmail.setText("");
        btnManagerCreate.setEnabled(true);
        tableManager.clearSelection();
        txtManagerName.setEnabled(true);
    }//GEN-LAST:event_btnManagerClearActionPerformed

    private void btnManagerbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerbackActionPerformed
    
        Main z = new Main();
        z.lblname.setText(lblname.getText());
        z.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManagerbackActionPerformed

    private void txtDayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDayKeyTyped
        char v = evt.getKeyChar();

        if(Character.isDigit(v)){
            evt.consume();
        }
    }//GEN-LAST:event_txtDayKeyTyped

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGender;
    private javax.swing.JButton btnManagerClear;
    private javax.swing.JButton btnManagerCreate;
    private javax.swing.JButton btnManagerDelete;
    private javax.swing.JButton btnManagerUpdate;
    private javax.swing.JButton btnManagerback;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblimage2;
    public javax.swing.JLabel lblname;
    private javax.swing.JTable tableManager;
    private javax.swing.JTextArea txtDay;
    private javax.swing.JTextField txtManagerAddress;
    private javax.swing.JTextField txtManagerContactNum;
    private javax.swing.JTextField txtManagerEmail;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtManagerPass;
    // End of variables declaration//GEN-END:variables
}
