/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment.sem.pkg1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bouoron
 */
public class Technician2 extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Technician2
     */
    public Technician2() {
        initComponents();
        
        String filePath = "Technician.txt";
        File file = new File(filePath);
    
        try {
            FileReader read = new FileReader(file);
            BufferedReader buffread = new BufferedReader(read);
            
            DefaultTableModel tablemode = (DefaultTableModel)tabletechnician1.getModel();
            Object[] lines = buffread.lines().toArray();
            
            for(int i =0; i < lines.length; i++){
                String[] row = lines[i].toString().split("///");
                tablemode.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Technician2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTechnicianID = new javax.swing.JTextField();
        txtTechnicianName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContactNum = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabletechnician = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblimage2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTechnicianPass1 = new javax.swing.JTextField();
        txtTechnicianName1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        txtContactNum1 = new javax.swing.JTextField();
        btnCreate1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabletechnician1 = new javax.swing.JTable();
        boxGender = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();

        txtTechnicianID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTechnicianIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Technician ID:");

        jLabel2.setText("Technician Name:");

        jLabel3.setText("Gender:");

        jLabel4.setText("Contact Number:");

        jLabel5.setText("Address:");

        jLabel6.setText("Email:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        tabletechnician.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Technician ID", "Technician Name", "Gender", "Contact Number", "Address", "Email"
            }
        ));
        jScrollPane2.setViewportView(tabletechnician);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTechnicianID, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtTechnicianName)
                            .addComponent(txtGender)
                            .addComponent(txtAddress)
                            .addComponent(txtEmail)
                            .addComponent(txtContactNum)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnCreate)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTechnicianID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTechnicianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        lblimage2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblimage2.setForeground(new java.awt.Color(255, 255, 255));
        lblimage2.setText("APU Hostel Appliances Service Centre");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("✺");

        jLabel16.setBackground(new java.awt.Color(0, 204, 204));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("X");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Manager");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtTechnicianPass1.setBackground(new java.awt.Color(255, 255, 255));
        txtTechnicianPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTechnicianPass1ActionPerformed(evt);
            }
        });

        txtTechnicianName1.setBackground(new java.awt.Color(255, 255, 255));
        txtTechnicianName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTechnicianName1ActionPerformed(evt);
            }
        });
        txtTechnicianName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTechnicianName1KeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Technician Password:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Technician Name:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Gender:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contact Number:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Address:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email:");

        txtEmail1.setBackground(new java.awt.Color(255, 255, 255));

        txtContactNum1.setBackground(new java.awt.Color(255, 255, 255));
        txtContactNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNum1ActionPerformed(evt);
            }
        });
        txtContactNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNum1KeyTyped(evt);
            }
        });

        btnCreate1.setBackground(new java.awt.Color(0, 204, 204));
        btnCreate1.setForeground(new java.awt.Color(0, 0, 0));
        btnCreate1.setText("Create");
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        tabletechnician1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Technician Name", "Technician Password", "Gender", "Contact Number", "Address", "Email", "Available Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabletechnician1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletechnician1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabletechnician1);

        boxGender.setBackground(new java.awt.Color(255, 255, 255));
        boxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        boxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGenderActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Technician Account Management");

        btnClear.setBackground(new java.awt.Color(0, 204, 204));
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(0, 204, 204));
        btnback.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Available day:");

        txtAddress1.setBackground(new java.awt.Color(255, 255, 255));

        txtDay.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail1)
                            .addComponent(txtContactNum1)
                            .addComponent(txtTechnicianPass1)
                            .addComponent(boxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTechnicianName1)
                            .addComponent(txtAddress1)
                            .addComponent(txtDay)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnCreate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnback))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTechnicianName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTechnicianPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContactNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel11))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate1)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnback)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblname)
                        .addGap(59, 59, 59))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblimage2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(39, 39, 39)
                        .addComponent(lblimage2)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTechnicianIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTechnicianIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTechnicianIDActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if(txtTechnicianID.getText().equals("")|| txtTechnicianName.getText().equals("")|| txtGender.getText().equals("")|| txtContactNum.getText().equals("")|| txtAddress.getText().equals("")|| txtEmail.getText().equals("")|| txtDay.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill in all Blank Textbox");
        }else{
            String TechData[] = {txtTechnicianID.getText(),txtTechnicianName.getText(),txtGender.getText(),txtContactNum.getText(),txtAddress.getText(),txtEmail.getText(),txtDay.getText()};

            DefaultTableModel table = (DefaultTableModel)tabletechnician.getModel();

            table.addRow(TechData);

            JOptionPane.showMessageDialog(this,"Created new Technician Account Successfully");
            txtTechnicianID.setText("");
            txtTechnicianName.setText("");
            txtGender.setText("");
            txtContactNum.setText("");
            txtAddress.setText("");
            txtEmail.setText("");
            txtDay.setText("");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtTechnicianPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTechnicianPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTechnicianPass1ActionPerformed

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        if(txtTechnicianName1.getText().equals("")||txtTechnicianPass1.getText().equals("")|| boxGender.getSelectedItem().equals("")|| txtContactNum1.getText().equals("")|| txtAddress1.getText().equals("")|| txtEmail1.getText().equals("")|| txtDay.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill in all Blank Textbox");
        }else{
            String s = "";
            boolean exists = false;
            for (int i = 0; i < tabletechnician1.getRowCount(); i++){
                s = tabletechnician1.getValueAt(i, 0).toString().trim();
            
                if(txtTechnicianName1.getText().equals(s)){
                    exists = true;
                    JOptionPane.showMessageDialog(null, "Name Exist, type another Name Please");
                    txtTechnicianName1.setText("");
                    
                    break;
                }
            }if(exists == false){
            String TechData[] = {txtTechnicianName1.getText(),txtTechnicianPass1.getText(),boxGender.getSelectedItem().toString(),txtContactNum1.getText(),txtAddress1.getText(),txtEmail1.getText(),txtDay.getText()};

            DefaultTableModel table = (DefaultTableModel)tabletechnician1.getModel();

            table.addRow(TechData);
            
            String filePath = "Technician.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);
                
                for(int i = 0; i < tabletechnician1.getRowCount(); i++){
                    for(int p = 0; p < tabletechnician1.getColumnCount(); p++){
                        buffwrite.write(tabletechnician1.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }
                
                
                buffwrite.close();
                write.close();
                
            } catch (IOException ex) {
                Logger.getLogger(Technician2.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this,"Created new Technician Account Successfully");
            txtTechnicianName1.setText("");
            txtTechnicianPass1.setText("");
            txtContactNum1.setText("");
            txtAddress1.setText("");
            txtEmail1.setText("");
            txtDay.setText("");
        }
    }//GEN-LAST:event_btnCreate1ActionPerformed
    }
    private void boxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGenderActionPerformed

    private void txtContactNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNum1KeyTyped
        char t = evt.getKeyChar();
        
        if(!Character.isDigit(t)){
            evt.consume();
        }
    }//GEN-LAST:event_txtContactNum1KeyTyped

    private void txtContactNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNum1ActionPerformed

    private void txtTechnicianName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTechnicianName1ActionPerformed
       
    }//GEN-LAST:event_txtTechnicianName1ActionPerformed

    private void txtTechnicianName1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTechnicianName1KeyTyped
        char v = evt.getKeyChar();
        
        if(Character.isDigit(v)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTechnicianName1KeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel table = (DefaultTableModel)tabletechnician1.getModel();
        
        if(tabletechnician1.getSelectedRowCount()==1){
            table.removeRow(tabletechnician1.getSelectedRow());
            
            String filePath = "Technician.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);
                
                for(int i = 0; i < tabletechnician1.getRowCount(); i++){
                    for(int p = 0; p < tabletechnician1.getColumnCount(); p++){
                        buffwrite.write(tabletechnician1.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }
                
                
                buffwrite.close();
                write.close();
                
            } catch (IOException ex) {
                Logger.getLogger(Technician2.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(this, "Successfully removed");
            txtTechnicianPass1.setText("");
            txtTechnicianName1.setText("");
            txtContactNum1.setText("");
            txtAddress1.setText("");
            txtEmail1.setText("");
            txtTechnicianName1.setEnabled(true);
            btnCreate1.setEnabled(true);
            txtDay.setText("");
            
        }else{
            if(tabletechnician1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "There are no data left in the table");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row to remove");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tabletechnician1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletechnician1MouseClicked

        
        DefaultTableModel table = (DefaultTableModel)tabletechnician1.getModel();
        
        String tableName = table.getValueAt(tabletechnician1.getSelectedRow(), 0).toString();
        String tablePass = table.getValueAt(tabletechnician1.getSelectedRow(), 1).toString();
        String tableGen = table.getValueAt(tabletechnician1.getSelectedRow(), 2).toString();
        for(int i = 0; i < boxGender.getItemCount(); i++){
            if(boxGender.getItemAt(i).equalsIgnoreCase(tableGen)){
                boxGender.setSelectedIndex(i);
            }
        }
        String tableContactNum = table.getValueAt(tabletechnician1.getSelectedRow(), 3).toString();
        String tableAddress = table.getValueAt(tabletechnician1.getSelectedRow(), 4).toString();
        String tableEmail = table.getValueAt(tabletechnician1.getSelectedRow(), 5).toString();
        String tableDay = table.getValueAt(tabletechnician1.getSelectedRow(), 6).toString();
        btnCreate1.setEnabled(false);
        txtTechnicianName1.setText(tableName);
        txtTechnicianPass1.setText(tablePass);
        txtContactNum1.setText(tableContactNum);
        txtAddress1.setText(tableAddress);
        txtEmail1.setText(tableEmail);
        txtDay.setText(tableDay);
        txtTechnicianName1.setEnabled(false);
    }//GEN-LAST:event_tabletechnician1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel table = (DefaultTableModel)tabletechnician1.getModel();
        
        if(txtTechnicianName1.getText().equals("")||txtTechnicianPass1.getText().equals("")|| boxGender.getSelectedItem().equals("")|| txtContactNum1.getText().equals("")|| txtAddress1.getText().equals("")|| txtEmail1.getText().equals("")|| txtDay.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill in all Blank Textbox");
        }else if(tabletechnician1.getSelectedRowCount() == 1){
            String Name = txtTechnicianName1.getText();
            String Password = txtTechnicianPass1.getText();
            String Gen = (String) boxGender.getSelectedItem();
            String ContactNum = txtContactNum1.getText();
            String Address = txtAddress1.getText();
            String Email = txtEmail1.getText();
            String Day = txtDay.getText();
            
            table.setValueAt(Name, tabletechnician1.getSelectedRow(), 0);
            table.setValueAt(Password, tabletechnician1.getSelectedRow(), 1);
            table.setValueAt(Gen, tabletechnician1.getSelectedRow(), 2);
            table.setValueAt(ContactNum, tabletechnician1.getSelectedRow(), 3);
            table.setValueAt(Address, tabletechnician1.getSelectedRow(), 4);
            table.setValueAt(Email, tabletechnician1.getSelectedRow(), 5);
            table.setValueAt(Day, tabletechnician1.getSelectedRow(), 6);
            
            JOptionPane.showMessageDialog(this, "Successfully updated!!");
            
            txtTechnicianPass1.setText("");
            txtTechnicianName1.setText("");
            txtContactNum1.setText("");
            txtAddress1.setText("");
            txtEmail1.setText("");
            txtDay.setText("");
            btnCreate1.setEnabled(true);
            tabletechnician1.clearSelection();
            txtTechnicianName1.setEnabled(true);
            
            String filePath = "Technician.txt";
            File file = new File(filePath);
            try {
                FileWriter write = new FileWriter(file);
                BufferedWriter buffwrite = new BufferedWriter(write);
                
                for(int i = 0; i < tabletechnician1.getRowCount(); i++){
                    for(int p = 0; p < tabletechnician1.getColumnCount(); p++){
                        buffwrite.write(tabletechnician1.getValueAt(i, p).toString()+"///");
                    }
                    buffwrite.newLine();
                }
                
                
                buffwrite.close();
                write.close();
                
            } catch (IOException ex) {
                Logger.getLogger(Technician2.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            if(table.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "There is no data on the table");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a list for update!");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtTechnicianPass1.setText("");
        txtTechnicianName1.setText("");
        txtContactNum1.setText("");
        txtAddress1.setText("");
        txtEmail1.setText("");
        txtDay.setText("");
        btnCreate1.setEnabled(true);    
        tabletechnician1.clearSelection();
        txtTechnicianName1.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        Main z = new Main();
        z.lblname.setText(lblname.getText());
        z.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Technician2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Technician2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Technician2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Technician2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGender;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblimage2;
    public javax.swing.JLabel lblname;
    private javax.swing.JTable tabletechnician;
    private javax.swing.JTable tabletechnician1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtContactNum;
    private javax.swing.JTextField txtContactNum1;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtTechnicianID;
    private javax.swing.JTextField txtTechnicianName;
    private javax.swing.JTextField txtTechnicianName1;
    private javax.swing.JTextField txtTechnicianPass1;
    // End of variables declaration//GEN-END:variables
}
